
    
usuario_login:
    pattern: /login
    defaults: { _controller: UsuarioBundle:Default:login }    


usuario_login_check:
    pattern: /login_check

usuario_logout:
    pattern: /logout
    
usuario_registro:
    pattern: /registro
    defaults: { _controller: UsuarioBundle:Default:registro }
    
usuario_perfil:
    pattern: /perfil-{username}
    defaults: { _controller: UsuarioBundle:Default:perfil }
    
usuario_recientes:
    pattern: /recientes
    defaults: { _controller: UsuarioBundle:Default:recientes }

confirmacion:
    pattern: /confirmacion/{id}
    defaults: { _controller: UsuarioBundle:Confirmacion:confirmacion }
    

    
    
    
    
    

    

    