parameters:
#    usuario.example.class: GameAffinity\UsuarioBundle\Example

services:
    usuario.loginlistener:
        class: GameAffinity\UsuarioBundle\Listener\LoginListener
        #arguments: [@router, @service_container]
        calls: 
            - [setContainer, [@service_container]] 
            - [setRouter, [@router]]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel_event_listener, event: kernel.response }
    
#    usuario.example:
#        class: %usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
