<?php

namespace GameAffinity\RedaccionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RedaccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedaccionRepository extends EntityRepository
{
    private function getConsulta($dql){
        $manager = $this->getEntityManager();
        $consulta = $manager->createQuery($dql);
        return $consulta;
    }
    
    public function findRedactorByUsername($redactor){
        $dql = 'select r from RedaccionBundle:Redaccion r '
                . 'where r.username = :username'
                ;
        $consulta = $this->getConsulta($dql);
        $consulta->setParameter('username', $redactor);
        return $consulta->getSingleResult()
                ;
    }
    
    
}
