<?php

namespace GameAffinity\DesarrolladorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DesarrolladorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesarrolladorRepository extends EntityRepository
{
    
    public function findJuegosPorDesarrollador($desarrollador){
        $manager=$this->getEntityManager();
        
        $dql="select j "
                ."from JuegoBundle:Juego j "
                . "where juego.desarrollador = :desarrollador";
        $result=$manager->createQuery($dql);
        $result->setParameter('desarrollador',$desarrollador);
        $juegos=$result->getArrayResult();
        return $juegos;
                
    }
    
}
