<?php

namespace GameAffinity\UsuarioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository {

    private function consulta($dql) {
        $manager = $this->getEntityManager();
        $consulta = $manager->createQuery($dql);
        return $consulta;
    }

    public function findPerfil($username) {
        $dql = "select u from UsuarioBundle:Usuario u where u.username=:username";
        $consulta = $this->consulta($dql);
        $consulta->setParameter('username', $username);
        return $consulta->getSingleResult();
    }

    public function findUserByCid($cid) {
        $dql = "select u from UsuarioBundle:Usuario u where u.cid=:cid";
        $consulta = $this->consulta($dql);
        $consulta->setParameter('cid', $cid);
        return $consulta->getSingleResult();
    }

}
