<?php

namespace GameAffinity\ValoracionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ValoracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoracionRepository extends EntityRepository {

    private function consulta($dql) {
        $manager = $this->getEntityManager();
        $consulta = $manager->createQuery($dql);
        return $consulta;
    }

    public function findValoracionesPorJuego($juego) {

        //$dql = "select v from ValoracionBundle:Valoracion v"
        $manager = $this->getEntityManager();

        $dql = "select v, p, u, r "
                . "from ValoracionBundle:Valoracion v "
                . "join v.post p "
                . "left join v.usuario u "
                . "left join v.redactor r "
                . "where p.slug = :post ";


        // $consulta = $this->consulta($dql);
        $consulta = $manager->createQuery($dql);
        $consulta->setParameter('post', $juego->getSlug());
        //$array_result=$consulta->getArrayResult();
        //var_dump($array_result);
        return $consulta->getArrayResult();
    }

    public function findValoracionesPorUsuario($usuario) {

        $dql = "select v, u, p "
                . "from ValoracionBundle:Valoracion v "
                . "join v.usuario u "
                . "join v.post p "
                . "where u = :usuario ";
        $consulta = $this->consulta($dql);
        $consulta->setParameter('usuario', $usuario->getId());
        //return $consulta->getArrayResult();
        return $consulta->getResult();
    }

}
